# Generated by Django 3.2.7 on 2021-10-05 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='game_id',
            new_name='game',
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetC', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Multi', 'Multi'), ('Blanc', 'Blanc')], max_length=6)),
                ('TargetS', models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Triangle', 'Triangle'), ('Hex', 'Hex'), ('Vortex', 'Vortex'), ('Blanc', 'Blanc')], max_length=8)),
                ('turn_number', models.IntegerField(default=0)),
                ('prev_posx', models.IntegerField()),
                ('prev_posy', models.IntegerField()),
                ('curr_posx', models.IntegerField()),
                ('curr_posy', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Multi', 'Multi'), ('Blanc', 'Blanc')], max_length=6)),
                ('symbol', models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Triangle', 'Triangle'), ('Hex', 'Hex'), ('Vortex', 'Vortex'), ('Blanc', 'Blanc')], max_length=8)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.game')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
