# Generated by Django 3.2.7 on 2021-10-14 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_square_obstacle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='curr_posx',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='curr_posy',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='prev_posx',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='prev_posy',
        ),
        migrations.AddField(
            model_name='turn',
            name='pos_black',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='pos_blue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='pos_green',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='pos_red',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='pos_yellow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='sequence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='TargetS',
            field=models.CharField(choices=[('Circle', 'Circle'), ('Square', 'Square'), ('Triangle', 'Triangle'), ('Hex', 'Hex'), ('Vortex', 'Vortex'), ('Blanc', 'Blanc')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='targetC',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Multi', 'Multi'), ('Blanc', 'Blanc')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
