# Generated by Django 3.2.7 on 2021-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('targets_remaining', models.IntegerField(default=17)),
            ],
        ),
    ]
