# Generated by Django 3.2.7 on 2021-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_player_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
