apiVersion: v1
kind: Service
metadata:
        name: robots-backend
        annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/port: '8000'
        labels:
                app: robots-backend
spec:
        type: NodePort
        selector:
                app: robots-backend
        ports:
                - port: 8000
                  targetPort: 8000
